### ISSUE TITLE
CI Failures

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cvxpy-feedstock#1]
Appears there are some CI failures on `master` for [Linux Python 3.5]( https://circleci.com/gh/conda-forge/cvxpy-feedstock/3 ), [macOS Python 3.5]( https://travis-ci.org/conda-forge/cvxpy-feedstock/jobs/396405414 ), and [macOS Python 3.6]( https://travis-ci.org/conda-forge/cvxpy-feedstock/jobs/396405415 ). The last two probably just need a restart.

**Comment by dougalsutherland** [comment]
Thanks for noticing and hitting rebuild. These seem to have all resolved, though I don't understand why they happened in the first place...
