### ISSUE TITLE
New CVXPY dependency: Clarabel

### ISSUE THREAD

**Issue by phschiele** [conda-forge/cvxpy-feedstock#82]
### Comment:

We are planning to add the [Clarabel](https://github.com/oxfordcontrol/Clarabel.rs) solver as a CVXPY dependency with the next release. So far, Clarabel is not available on conda.
I suppose the preferred way would be add Clarabel to conda, but I wanted to check if this is a hard requirement immediately.

CC: @h-vetinari @goulart-paul @SteveDiamond

**Comment by h-vetinari** [comment]
Thanks for the heads-up, always good to know in advance rather than be surprised upon release.

We will need to add clarabel to conda in order to support the next cvxpy version, yes.

**Comment by goulart-paul** [comment]
Working on conda recipe here: https://github.com/conda-forge/staged-recipes/pull/24077

**Comment by goulart-paul** [comment]
This looks to be working now and is just waiting on review and approval.

**Comment by phschiele** [comment]
Ping @h-vetinari, we are about to release 1.4. Do you mind giving https://github.com/conda-forge/staged-recipes/pull/24077 a review?

**Comment by goulart-paul** [comment]
Clarabel recipe referred to above has been merged.   Thanks to @h-vetinari for reviewing.

**Comment by phschiele** [comment]
Thanks @h-vetinari and @goulart-paul!

**Comment by h-vetinari** [comment]
We still need to build clarabel for the non-x64 arches, but that's not as big a step as getting through staged recipes in the first place. ;)
